# -*- coding: utf-8 -*-
"""EjerciciosResueltos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dLqGZMtKREFklhEtvYqsYUGJWqUshSlp

# Ejercicios

- Ejercicio 1:
"""

import requests
from bs4 import BeautifulSoup

def get_html(url):
    """Obtiene el HTML de la URL especificada."""
    try:
        response = requests.get(url)
        response.raise_for_status()  # Lanza error en caso de códigos de respuesta 4xx o 5xx.
        return response.text
    except requests.RequestException as e:
        print(f"Error al conectar con {url}: {e}")
        return None

def getTitle(url):
    """Retorna el contenido de la etiqueta <title> de la URL."""
    html = get_html(url)
    if html:
        soup = BeautifulSoup(html, 'html.parser')
        title_tag = soup.find('title')
        if title_tag:
            return title_tag.get_text(strip=True)
    return None

def getDiv(url):
    """Retorna el primer elemento <div> de la URL."""
    html = get_html(url)
    if html:
        soup = BeautifulSoup(html, 'html.parser')
        div_tag = soup.find('div')
        if div_tag:
            return div_tag
    return None

def getMeta(url):
    """Retorna el primer elemento <meta> de la URL."""
    html = get_html(url)
    if html:
        soup = BeautifulSoup(html, 'html.parser')
        meta_tag = soup.find('meta')
        if meta_tag:
            return meta_tag
    return None

def getLink(url):
    """Retorna el primer elemento <a> (link) de la URL."""
    html = get_html(url)
    if html:
        soup = BeautifulSoup(html, 'html.parser')
        link_tag = soup.find('a')
        if link_tag:
            return link_tag
    return None

# Ejemplo de uso
#if __name__ == "__main__":
url = "https://daw2-test1.vercel.app/"  # Cambiar por la URL deseada
title = getTitle(url)
print("Title:", title)

div_element = getDiv(url)
print("Primer div:", div_element)

meta_element = getMeta(url)
print("Primer meta:", meta_element)

link_element = getLink(url)
print("Primer link:", link_element)

"""# Ejercicio 2"""

import requests
from bs4 import BeautifulSoup
from urllib.parse import urljoin

# Obtenemos la información
url_base = 'https://exactas.uba.ar/'
endpoint_grado = '/ensenanza/carreras-de-grado/'
html_obtenido = requests.get(url_base + endpoint_grado)
soup = BeautifulSoup(html_obtenido.text, "html.parser")

# La parseamos
ul = soup.find('ul', class_ = "listado carreras grado")
for li in ul.find_all('li'):
    print(f"{li.h2.text} {li.a['href']}")